services:
  server:
    build:
      context: .
    ports:
      - 8000:8000

  migrate_db:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: naukri_migrate_db
    command: sh -c "python3 manage.py makemigrations --noinput && python3 manage.py migrate auth && python3 manage.py migrate contenttypes && python3 manage.py migrate admin && python3 manage.py migrate sessions && python3 manage.py migrate --noinput && python3 manage.py createcachetable"
    env_file:
      - .env
    depends_on:
      - backend
    restart: "no"

  migrate_setup:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: naukri_migrate_setup
    command: sh -c "python3 manage.py create_superuser && python3 manage.py collectstatic --noinput"
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - migrate_db
    restart: "no"