# Generated by Django 5.1.4 on 2025-01-09 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_initial'),
        ('settings', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='business_unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.businessunitsettings'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.departmentsettings'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='designation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.designationsettings'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_code',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
