# Generated by Django 5.1.4 on 2025-01-16 04:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('module', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('applicable_to', models.CharField(max_length=50)),
                ('no_of_document', models.IntegerField()),
                ('expiry_date', models.BooleanField()),
                ('mandatory', models.BooleanField()),
                ('identification', models.BooleanField()),
                ('issue_date', models.BooleanField()),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeProfileSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manage_employee_profile', models.CharField(choices=[('allowed', 'allowed'), ('limited', 'limited'), ('blocked', 'blocked')], max_length=50)),
                ('unique_fields', models.JSONField()),
                ('employee_skills', models.CharField(choices=[('1-3', '1-3'), ('1-5', '1-5'), ('1-10', '1-10'), ('custom', 'custom')], max_length=50)),
                ('custom_skills', models.JSONField(blank=True, null=True)),
                ('approve_required', models.BooleanField(default=False)),
                ('employees_addable', models.BooleanField(default=False)),
                ('filter_search', models.BooleanField(default=False)),
                ('generally_showable_fields', models.JSONField(default={'email': False, 'employee_status': False, 'profile_image': False})),
                ('officially_showable_fields', models.JSONField(default={'department': False, 'designation': False, 'employee_code': False, 'joining_date': False, 'location': False, 'reporting_manager': False})),
                ('contacts_showable_fields', models.JSONField(default={'address': False, 'email': False, 'linked': False, 'mobile': False})),
                ('other_showable_fields', models.JSONField(default={'about_me': False, 'attendance_status': False, 'employment_type': False, 'service_status': False, 'skills': False})),
                ('mandatory_inputable_fields', models.JSONField(default={'bank_details': False, 'certifications': False, 'documents': False, 'education_details': False, 'emergency_contact': False, 'family_details': False, 'job_history': False, 'profile_image': False})),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
