# Generated by Django 5.1.4 on 2025-07-31 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_billingsettings_updated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='regularizationpolicies',
            name='enable_attendance_approval_manager',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='regularizationpolicies',
            name='enable_duty_punch_employee',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='regularizationpolicies',
            name='enable_early_exit_justify_manager',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='regularizationpolicies',
            name='enable_late_justify_manager',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='regularizationpolicies',
            name='enable_punch_request_manager',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='regularizationpolicies',
            name='enable_real_time_justify_employee',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='regularizationpolicies',
            name='enable_total_time_justify_manager',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
