# Generated by Django 5.1.4 on 2025-08-04 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_regularizationpolicies_enable_attendance_approval_manager_and_more'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentsetting',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.organization'),
        ),
        migrations.AddField(
            model_name='employeeprofilesettings',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.organization'),
        ),
    ]
