# Generated by Django 5.1.4 on 2025-08-04 10:11

import settings.employee_settings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0007_employeeprofilesettings_updated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofilesettings',
            name='contacts_showable_fields',
            field=models.JSONField(default=settings.employee_settings.models.default_contacts_showable_fields),
        ),
        migrations.AlterField(
            model_name='employeeprofilesettings',
            name='generally_showable_fields',
            field=models.JSONField(default=settings.employee_settings.models.default_generally_showable_fields),
        ),
        migrations.AlterField(
            model_name='employeeprofilesettings',
            name='mandatory_inputable_fields',
            field=models.JSONField(default=settings.employee_settings.models.default_mandatory_inputable_fields),
        ),
        migrations.AlterField(
            model_name='employeeprofilesettings',
            name='officially_showable_fields',
            field=models.JSONField(default=settings.employee_settings.models.default_officially_showable_fields),
        ),
        migrations.AlterField(
            model_name='employeeprofilesettings',
            name='other_showable_fields',
            field=models.JSONField(default=settings.employee_settings.models.default_other_showable_fields),
        ),
    ]
