# Generated by Django 5.1.4 on 2025-01-09 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='name',
            new_name='organization_name',
        ),
    ]
